.MODEL SMALL
.STACK 100H 

.DATA
    ARRAY DB 5 DUP(?)
    COUNT DW 5
    SUM DW ?
    AVERAGE DB ?
    LARGEST DB ?
    SMALLEST DB ? 

.CODE   
MAIN PROC
    MOV AX, @DATA
    MOV DS, AX

    CALL GET_INPUT
    CALL CALCULATE_AVERAGE
    CALL FIND_LARGEST
    CALL FIND_SMALLEST



    MOV AH, 4CH
    INT 21H
MAIN ENDP    

GET_INPUT PROC 
   
    MOV SI, OFFSET ARRAY
    MOV CX, COUNT 
    
    INPUT:
    MOV AH, 01H
    INT 21H
    SUB AL, 30H
    MOV [SI], AL
    INC SI
    LOOP INPUT
    RET 
GET_INPUT ENDP 

CALCULATE_AVERAGE PROC
    MOV SI, OFFSET ARRAY
    MOV CX, COUNT
    MOV SUM, 0

    AVG:
    MOV AL, [SI]
    ADD SUM, AX
    INC SI
    LOOP AVG

    MOV AX, SUM
    MOV BX, COUNT
    DIV BX
    MOV AVERAGE, AL
    RET 
CALCULATE_AVERAGE ENDP   

FIND_LARGEST PROC
    MOV SI, OFFSET ARRAY
    MOV CX, COUNT
    MOV AL, [SI]
    MOV LARGEST, AL

    LAR:
    INC SI
    MOV AL, [SI]
    CMP AL, LARGEST
    JBE NOT_LARGER
    MOV LARGEST, AL
    NOT_LARGER:
    LOOP LAR
    RET
    FIND_LARGEST ENDP

FIND_SMALLEST PROC
    MOV SI, OFFSET ARRAY
    MOV CX, COUNT
    MOV AL, [SI]
    MOV SMALLEST, AL

    SMA:
    INC SI
    MOV AL, [SI]
    CMP AL, SMALLEST
    JAE NOT_SMALLER
    MOV SMALLEST, AL
    NOT_SMALLER:
    LOOP SMA
    RET 
FIND_SMALLEST ENDP 


END MAIN